### ISSUE TITLE
can't open replies to message

### ISSUE THREAD

**Issue by Kikubernetes** [dangarfield/slack-back-static#1]
HI,

Thank you for disclosing nice script!
I can see messages and files locally now, but can't open replies to message. Is this as you intended?

**Comment by dangarfield** [comment]
Hi, that's a good point. I haven't added that because I didn't need it, but I'll add it next week. Feel free to add a PR if you can't wait until then.

**Comment by Kikubernetes** [comment]
Thanks a lot for response.
To be honest, I can't wait, because I'm a free member of slack・・・

**Comment by dangarfield** [comment]
That's a little rude, I'm actually on holiday.
I've briefly added the functionality to download the messages, but not display them properly yet. I'll add that next week when I'm home.

If you pull the latest code, it'll keep fetch all of the message replies. I'll leave this open until I add the UI component another time.

**Comment by dangarfield** [comment]
No matter, I had a few minutes. I've added the replies UI too. Just not for the search.
I'll close this ticket as it's in the main branch.
It would be interesting to know what use case you are looking at. PM me or open more tickets for enhancements (politely).
